"""Generate docs/CLI_REFERENCE.md from the real command tree, so the reference cannot drift.

python scripts/gen_cli_reference.py
"""

import sys
from pathlib import Path

import typer
import typer.main

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from stratos.cli.app import app  # noqa: E402
from stratos.domain.enums import ExitCode  # noqa: E402

EXIT_MEANING = {
    ExitCode.SUCCESS: "Success",
    ExitCode.GENERAL_ERROR: "General error",
    ExitCode.INVALID_USAGE: "Invalid usage (bad command line)",
    ExitCode.AUTHENTICATION: "Authentication failure (not signed in, bad credentials)",
    ExitCode.AUTHORIZATION: "Authorisation failure (missing permission or blocked by policy)",
    ExitCode.NOT_FOUND: "Resource not found",
    ExitCode.VALIDATION: "Validation failure (bad input)",
    ExitCode.NETWORK: "Network or API error",
    ExitCode.CONFIGURATION: "Configuration error",
    ExitCode.DEPENDENCY: "Dependency error (missing tool, failed `doctor` check)",
    ExitCode.CANCELLED: "Operation cancelled",
}


_SKIP = {"--help", "--install-completion", "--show-completion"}


def param_rows(cmd: object) -> list[str]:
    rows: list[str] = []
    for p in getattr(cmd, "params", []):
        is_argument = getattr(p, "param_type_name", "") == "argument"
        opts = [] if is_argument else list(getattr(p, "opts", []) or [])
        if opts and set(opts) <= _SKIP:
            continue
        label = ", ".join(f"`{o}`" for o in opts) if opts else f"`{p.name.upper()}`"
        default = getattr(p, "default", None)
        shown = "" if default in (None, (), [], False) else f" (default: `{default}`)"
        required = " **required**" if is_argument and getattr(p, "required", False) else ""
        kind = "argument" if is_argument else "option"
        rows.append(f"| {label} | {kind}{required} | {getattr(p, 'help', '') or ''}{shown} |")
    return rows


TABLE_HEAD = "| Name | Kind | Description |\n|---|---|---|"


def walk(cmd: object, path: list[str], ctx: typer.Context, out: list[str]) -> None:
    name = " ".join(path)
    is_group = hasattr(cmd, "list_commands")
    if not is_group or path == ["stratos"]:
        pass
    heading = "##" if len(path) == 2 else "###"
    if len(path) > 1:
        out.append(f"{heading} `{name}`\n")
        help_text = (getattr(cmd, "help", "") or "").strip().split("\n\n")[0]
        if help_text:
            out.append(f"{help_text}\n")
        if not is_group:
            out.append("```\n" + cmd.get_usage(ctx).replace("Usage: ", "") + "\n```\n")  # type: ignore[attr-defined]
        rows = param_rows(cmd)
        if rows:
            out.append(TABLE_HEAD)
            out.extend(rows)
            out.append("")
    if is_group:
        for sub in cmd.list_commands(ctx):  # type: ignore[attr-defined]
            child = cmd.get_command(ctx, sub)  # type: ignore[attr-defined]
            if child is not None and hasattr(child, "load"):
                child = child.load()  # lazy placeholders stand in for the real command
            if child is None:
                continue
            child_ctx = typer.Context(child, info_name=sub, parent=ctx)
            walk(child, [*path, sub], child_ctx, out)


def main() -> None:
    root = typer.main.get_command(app)
    ctx = typer.Context(root, info_name="stratos")
    out = [
        "# CLI reference\n",
        "_Generated by `scripts/gen_cli_reference.py`; do not edit by hand._\n",
        "## Global options\n",
        TABLE_HEAD,
        *param_rows(root),
        "",
        "Every mutating command also accepts `--dry-run` (preview, change nothing) and, where it "
        "asks for confirmation, `--yes` (skip the prompt).\n",
    ]
    walk(root, ["stratos"], ctx, out)
    out += ["## Exit codes\n", "| Code | Meaning |\n|---|---|"]
    out += [f"| {int(code)} | {text} |" for code, text in EXIT_MEANING.items()]
    out += [
        "",
        "## Environment variables\n",
        "See `.env.example`. Settings use `STRATOS_<SECTION>__<KEY>`; credentials use provider "
        "variables such as `GITHUB_TOKEN` and `ANTHROPIC_API_KEY`.\n",
    ]
    target = ROOT / "docs" / "CLI_REFERENCE.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target} ({len(out)} blocks)")


if __name__ == "__main__":
    main()
